export const UslugiData = [
  {
    id: 1,
    name: "Терапия",
    description: "Описание услуги Терапия",
    price: 100,
    image: "https://static.tildacdn.com/tild6232-3835-4630-a263-353533313037/image.png",
  },
  {
    id: 2,
    name: "ЛОР",
    description: "Описание услуги ЛОР",
    price: 200,
    image: "https://via.placeholder.com/150",
  },
  {
    id: 3,
    name: "Неврология",
    description: "Описание услуги Неврология",
    price: 300,
    image: "https://via.placeholder.com/150",
  },
  {
    id: 4,
    name: "Кардиология",
    description: "Описание услуги Кардиология",
    price: 300,
    image: "https://via.placeholder.com/150",
  },
  {
    id: 5,
    name: "Стоматология",
    description: "Описание услуги Стоматология",
    price: 300,
    image: "https://via.placeholder.com/150",
  },{
    id: 6,
    name: "Врач педиатр",
    description: "Описание услуги Врач педиатр",
    price: 100,
    image: "https://via.placeholder.com/150",
  },
  {
    id: 7,
    name: "Детский ЛОР",
    description: "Описание услуги Детский ЛОР",
    price: 200,
    image: "https://via.placeholder.com/150",
  },
  {
    id: 8,
    name: "Детский психолог",
    description: "Описание услуги Детский психолог",
    price: 300,
    image: "https://via.placeholder.com/150",
  },
  {
    id: 9,
    name: "Детский невропатолог",
    description: "Описание услуги Детский невропатолог",
    price: 300,
    image: "https://via.placeholder.com/150",
  },
  {
    id: 10,
    name: "Узи детям",
    description: "Описание услуги Узи детям",
    price: 300,
    image: "https://via.placeholder.com/150",
  },{
    id: 11,
    name: "Общеклинческие анализы",
    description: "Описание услуги Общеклинические анализы",
    price: 100,
    image: "https://via.placeholder.com/150",
  },
  {
    id: 12,
    name: "Общехимический анализ крови",
    description: "Описание услуги Общехимический анализ крови",
    price: 200,
    image: "https://via.placeholder.com/150",
  },
  {
    id: 13,
    name: "Иммунофертный анализ",
    description: "Описание услуги Иммунофертный анализ",
    price: 300,
    image: "https://via.placeholder.com/150",
  },
  {
    id: 14,
    name: "Серологическое исследование",
    description: "Описание услуги Серологическое исследование",
    price: 300,
    image: "https://via.placeholder.com/150",
  },
  {
    id: 15,
    name: "Гастроскопия",
    description: "Описание услуги Гастроскопия",
    price: 300,
    image: "https://via.placeholder.com/150",
  },{
    id: 16,
    name: "Хирургические операции",
    description: "Описание услуги Хирургические операции",
    price: 100,
    image: "https://via.placeholder.com/150",
  },
  {
    id: 17,
    name: "ЛОР-операции",
    description: "Описание услуги ЛОР-операции",
    price: 200,
    image: "https://via.placeholder.com/150",
  },
  {
    id: 18,
    name: "Челюстно-лицевая хирургия",
    description: "Описание услуги Челюстно-лицевая хирургия",
    price: 300,
    image: "https://via.placeholder.com/150",
  },
  {
    id: 19,
    name: "Сосудистая хирургия",
    description: "Описание услуги Сосудистая хирургия",
    price: 300,
    image: "https://via.placeholder.com/150",
  },
  {
    id: 20,
    name: "Анестезиология",
    description: "Описание услуги Анестезеология",
    price: 300,
    image: "https://via.placeholder.com/150",
  }
];
